[package]
edition.workspace = true
license.workspace = true
name = "katana-node"
repository.workspace = true
version.workspace = true

[dependencies]
katana-chain-spec.workspace = true
katana-core.workspace = true
katana-db.workspace = true
katana-executor.workspace = true
katana-gas-oracle.workspace = true
katana-log.workspace = true
katana-messaging.workspace = true
katana-metrics.workspace = true
katana-pipeline.workspace = true
katana-pool.workspace = true
katana-primitives.workspace = true
katana-provider.workspace = true
katana-rpc = { workspace = true }
katana-rpc-api.workspace = true
katana-stage.workspace = true
katana-tasks.workspace = true

anyhow.workspace = true
futures.workspace = true
http.workspace = true
jsonrpsee.workspace = true
serde.workspace = true
serde_json.workspace = true
starknet.workspace = true
thiserror.workspace = true
toml.workspace = true
tower = { workspace = true, features = [ "full" ] }
tower-http = { workspace = true, features = [ "full" ] }
tracing.workspace = true
url.workspace = true

strum.workspace = true
strum_macros.workspace = true

clap = { workspace = true, optional = true }
dojo-utils = { workspace = true, optional = true }
katana-feeder-gateway = { workspace = true, optional = true }
tokio = { workspace = true, features = [ "time" ], optional = true }
tracing-log = { workspace = true, optional = true }
tracing-subscriber = { workspace = true, optional = true }

[features]
cartridge = [ "katana-rpc-api/cartridge", "katana-rpc/cartridge" ]
native = [ "katana-executor/native" ]
# experimental feature to test katana full node mode
full-node = [ "dep:katana-feeder-gateway", "dep:tokio" ]

[[bin]]
name = "full-node"
path = "src/full/node.rs"
required-features = [
	"clap",
	"dojo-utils",
	"full-node",
	"tracing-log",
	"tracing-subscriber",
]
