[package]
description = "A fast and lightweight local Starknet development sequencer."
edition.workspace = true
license-file.workspace = true
name = "katana"
repository.workspace = true
version.workspace = true

[dependencies]
katana-chain-spec.workspace = true
katana-cli.workspace = true
katana-db = { workspace = true, features = [ "arbitrary" ] }
katana-primitives.workspace = true
katana-rpc-types.workspace = true
katana-utils.workspace = true

anyhow.workspace = true
async-trait.workspace = true
byte-unit = "5.1.4"
cainome.workspace = true
clap.workspace = true
clap_complete.workspace = true
comfy-table = "7.1.1"
const_format = "0.2.33"
indicatif = "0.17.8"
inquire = "0.7.5"
# Rev on branch starknet 0.15.1.
piltover = { git = "https://github.com/cartridge-gg/piltover.git", rev = "3bed7ac554259668dbdce6a5f56de5b2bf7faf43" }
rand.workspace = true
shellexpand = "3.1.0"
spinoff.workspace = true
starknet.workspace = true
strum_macros.workspace = true
thiserror.workspace = true
tokio.workspace = true
tracing.workspace = true
url.workspace = true

colored_json = { version = "5.0", optional = true }
serde = { workspace = true, optional = true }
serde_json = { workspace = true, optional = true }

[build-dependencies]
vergen = { version = "9.0.0", features = [ "build", "cargo", "emit_and_set" ] }
vergen-gitcl = { version = "1.0.0", features = [ "build", "cargo", "rustc", "si" ] }

[dev-dependencies]
katana-provider.workspace = true

arbitrary.workspace = true
assert_matches.workspace = true
proptest = "1.0"
rstest.workspace = true
tempfile.workspace = true

[features]
default = [ "cartridge", "init-slot", "jemalloc", "katana-cli/explorer" ]

cartridge = [ "katana-cli/cartridge" ]
client = [ "dep:colored_json", "dep:serde", "dep:serde_json" ]
init-custom-settlement-chain = [  ]
init-slot = [  ]
jemalloc = [  ]
native = [ "katana-cli/native" ]
